import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Irati Electricidad - Instalaciones electricas, redes y telefonia en pamplona",
  description: "Generated by create next app",
  keywords: ["Electricista", " Pamplona", "Irati", "Instalaciones telefonicas", "Istalaciones electricas"],
  icons: [{ href: "./favicon.ico", url: "./icon.ico" }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
