/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/94ZEXOLlLYb
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Header from "./Header/Header"
import Presentation from "./Sections/Presentation/Presentation"
import Services from "./Sections/Services/Services"

export function HomePage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <Header />
        <Presentation />
        <Services />
        <section className="w-full py-12 md:py-24">
          <div className="container grid items-center gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Testimonials</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Don't just take our word for it. Here's what our customers have to say about our services.
              </p>
            </div>
            <div className="grid gap-4 sm:gap-6">
              <div className="space-y-2">
                <h3 className="text-xl font-semibold">Professional Service</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  "The plumber arrived on time and was very professional. He quickly identified the issue with my pipes
                  and made the necessary repairs. My plumbing has been working perfectly ever since. I highly recommend
                  their services."
                </p>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-semibold">Prompt Response</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  "I called the plumbing service when I had a leak in my bathroom, and they were at my house within the
                  hour. The plumber was friendly and knowledgeable, and he fixed the issue quickly. I was very impressed
                  with their prompt response and the quality of their work."
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24">
          <div className="container grid items-center gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Us</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Ready to experience the best plumbing services in town? Contact us to schedule an appointment or request
                a quote.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="space-y-4">
                <Input
                  className="w-full border-gray-200 dark:border-gray-800"
                  placeholder="Name"
                  type="text"
                />
                <Input
                  className="w-full border-gray-200 dark:border-gray-800"
                  placeholder="Email"
                  type="email"
                />
                <Textarea className="w-full" placeholder="Message" />
                <Button className="w-full" type="submit">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function WrenchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
    </svg>
  )
}


