/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/94ZEXOLlLYb
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Header from "./Header/Header"
import Presentation from "./Sections/Presentation/Presentation"
import Services from "./Sections/Services/Services"
import Testimonial from "./Sections/Testimonial/Testimonial"
import Contact from "./Sections/Contact/Contact"

export function HomePage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <Header />
        <Presentation />
        <Services />
        <Testimonial />
        <Contact />
      </main>
      <footer className="flex flex-col gap-2 py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}



